ports:
  - port: 8080
    onOpen: open-preview
    
tasks:
  - init: >
      go build -o app
    command: >
      ./app
github:
    prebuilds:
        pullRequestsFromForks: true
vscode:
  extensions:
    - golang.go
